### ISSUE TITLE
Getting recent versions of TFP merged

### ISSUE THREAD

**Issue by MichaelRGrant** [conda-forge/tensorflow-probability-feedstock#23]
Issue: 
I am trying to build a package that uses tensorflow-probability and depends on conda-forge. I need a more recent version (>0.8) for this work and currently I'm stuck because the PRs opened for more recent versions of TFP have not been merged. I'm not sure if this is the right place for this request, but I was hoping that those PRs could have another look and get merged. 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by mayou36** [comment]
Hi all, it is the same for us. Why are these PR not merged, is there any special reason? I've looked through things but don't seem to find something specific
