### ISSUE TITLE
Tensorflow-probability conda forge package broken

### ISSUE THREAD

**Issue by SebastianBodza** [conda-forge/tensorflow-probability-feedstock#28]
When installing the Tensorflow-probability package from conda-forge it installs tensorflow-base with tf version 2.3. TF-probability however needs at least TF 2.4 to run. So when importing tf it imports tf 2.3 and tf agents can't be imported properly. 

https://anaconda.org/conda-forge/tensorflow-probability

**Comment by jonas-eschle** [comment]
@SebastianBo1995 for which tensorflow-probability version? Do you think this is still worth fixing? We can, just let us know the exact version that is broken

**Comment by mjpaden** [comment]
@jonas-eschle from what I can tell, the current version 0.17.0 is similarly broken upon install:

> This version of TensorFlow Probability requires TensorFlow version >= 2.9; Detected an installation of version 2.8.1. Please upgrade TensorFlow to proceed.
