### ISSUE TITLE
Patch metadata on older builds

### ISSUE THREAD

**Issue by mfansler** [conda-forge/tensorflow-probability-feedstock#40]
The loose constraints on `tensorflow-base` in all builds prior to v0.16.0 lead to environment solves with incompatible versions of `tensorflow` and `tensorflow-probability` (see [a recent example on StackOverflow](https://stackoverflow.com/q/74875266/570918)). The metadata on these packages should be updated to correct this. That is, declared compatibilities in [the Release Notes](https://github.com/tensorflow/probability/releases) should be consulted and a patch should be issued via [`conda-forge-repodata-patches`](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) (see [docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages)).

For a concrete example, `tensorflow-probability=0.15.0` currently allows `tensorflow-base>=2,<3`, but should have `tensorflow-base=2.7`. Some of the early builds (e.g., `0.6.0`) don't even include a `tensorflow-base` dependency.

**Comment by jonas-eschle** [comment]
Hm, I agree with the core issue. It's a hard requirement though as sometimes other TF versions also work, technically. But I agree that if a specific version is already mentioned, we should do that.

Possibly breaking envs, but rather preventing bugs that were not intended.

**Comment by jonas-eschle** [comment]
Just to make sure, JAX should be fixed to to the minor revision version, but not the patch version either, right? I.e. `jax ~= 0.3.0` (TFPs release note give sometimes the exact patch version)

**Comment by jonas-eschle** [comment]
Changes are added here https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/401

@mfansler, would you mind checking it?

I've ignored older builds that go against TF1 as this seems to be rather outdated by now

**Comment by mfansler** [comment]
@jonas-eschle, thanks for working on this! Everything you've added looks perfect.

Unfortunately, the older builds cannot be ignore: the solver will surface to be the problem once the newer ones are properly constrained. They must at least be upper-bounded with `tensorflow-base <2`.

**Comment by jonas-eschle** [comment]
I've constrained them too, gonna merge if there's nothing from your side

**Comment by jonas-eschle** [comment]
This has been fixed since a while, closing
