### ISSUE TITLE
relax Jax requirement

### ISSUE THREAD

**Issue by ngam** [conda-forge/tensorflow-probability-feedstock#45]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Can we relax Jax to a newer version, say 0.4.x?

https://github.com/conda-forge/staged-recipes/pull/23226

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jonas-eschle** [comment]
Okay, makes sense, and usually, TFP and TF aren't lagging that much behind, it's a bit of an exception.

**Comment by Muff2n** [comment]
I second this - the hard jax version requirement is making tensorflow-probability difficult to play nice with other libraries.

**Comment by jonas-eschle** [comment]
> I second this - the hard jax version requirement is making tensorflow-probability difficult to play nice with other libraries.

That's true, although that is probably best for the JAX devs to decide and we'll follow here the strategy that they use on pypi?
Or what would you propose @Muff2n ?
