### ISSUE TITLE
Only version 0.5.0 deployed.

### ISSUE THREAD

**Issue by jendelel** [conda-forge/tensorflow-probability-feedstock#5]
Issue:
Hi, 

why is there only version 0.5.0 on the [official channel](https://anaconda.org/conda-forge/tensorflow-probability) when this repository already has 0.6.0 version? How can I install the 0.6.0 version? 

Thanks, 

Lukas

**Comment by sodre** [comment]
Hi @jendelel the problem was related to the version of tensor flow that 0.6.0 required. I will check if it has been fixed.
