### ISSUE TITLE
Can conda-forge include 0.7.0?

### ISSUE THREAD

**Issue by cc20002002** [conda-forge/tensorflow-probability-feedstock#8]
Hi,

Can conda-forge include version 0.7.0? 

I was told conda-forge's tensorflow is faster than pip's . Is the same speed improvement applied to the tensorflow probability package?

Cheers,

Chen

**Comment by adbeda** [comment]
@cc20002002 just updated to 0.7.0. will hopefully get it accepted soon.

**Comment by mariusvniekerk** [comment]
feel free to add yourself to the maintainer team for this feedstock

**Comment by sodre** [comment]
tensorflow-probability 0.7.0 is currently available on conda-forge.
